global using Marten;
global using Mapster;
global using MediatR;
global using BuildingBlocks.CQRS.Handlers;
global using BuildingBlocks.CQRS.Requests;
global using FluentValidation;
global using BuildingBlocks.Behaviours;
global using Carter;
global using Basket.API.Models;